/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */
typedef volatile unsigned int vuint32_t;

#include <stdint.h>

//RCC enable for GPIO
#define RCC_BASE       0x40021000
#define RCC_APB2ENR   *((volatile uint32_t *) (RCC_BASE + 0x18))
#define RCC_IO 		   (1<<2)

//GPIO
#define PORTA_BASE     0x40010800
#define GPIOA_CRH   *((volatile uint32_t *) (PORTA_BASE + 0x04))
#define GPIOA_ODR   *((volatile uint32_t *) (PORTA_BASE + 0x0c))
#define GPIOA_CRL   *((volatile uint32_t *) (PORTA_BASE + 0x00))
#define AFIO_BASE	0x40010000
#define AFIO_EXTICR1 *((volatile uint32_t *) (AFIO_BASE + 0x08))



//EXIT0
#define EXTI_base   0x40010400
#define EXTI_IMR    *((volatile uint32_t*)(EXTI_base + 0x00))
#define EXTI_RTSR	*((volatile uint32_t*)(EXTI_base + 0x08))
#define EXTI_PR		*((volatile uint32_t*)(EXTI_base + 0x14))

//NVIC
#define NVIC_ISER0	*((volatile uint32_t*)(0xE000E100))

void clock_init()
{
	//enable clock for GPIO
	RCC_APB2ENR |= RCC_IO;

	//enable clock for AFIO
	RCC_APB2ENR |= 1<<0 ;
}
void GPIO_int()
{
	GPIOA_CRH &= 0xff0fffff; //to protect the bits
	GPIOA_CRH |= 0x00200000; //to make bits(20>>24)=2
	//pin A0 floating input
	GPIOA_CRL |= 1<<2 ;

}
int main(void)
{
	clock_init();
	GPIO_int();
	//Select PORTA for EXIT0     0000: PA[x] pin
	AFIO_EXTICR1 = 0x0;

	//Rising trigger enabled for PORTA->pin 0

	EXTI_RTSR |= 1<<0 ;


	//enable the mask for POTA->pin 0
	EXTI_IMR |= 1<<0 ;

	//enable NVIC for IQR6
	NVIC_ISER0 |= 1<<6 ;
	while(1);

	return 0;

}

void EXTI0_IRQHandler()
{
	//IQR happened EXIT0 PORTA->pin0 rising _|
	// toggle pin 13
	GPIOA_ODR ^= (1<<13);
	//clear pending request for line 0
	EXTI_PR |= 1<<0 ;


}
